sudo: required
services:
  - docker

before_install:
  - docker build -t tasfeqhub/docker-fibonacci-app -f ./client/Dockerfile.dev ./client
 
script:
  - docker run -e CI=true tasfeqhub/docker-fibonacci-app npm run test

after_success:
  - docker build -t tasfeqhub/fibonacci-client ./client
  - docker build -t tasfeqhub/fibonacci-nginx ./nginx
  - docker build -t tasfeqhub/fibonacci-server ./server
  - docker build -t tasfeqhub/fibonacci-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push tasfeqhub/fibonacci-client
  - docker push tasfeqhub/fibonacci-nginx
  - docker push tasfeqhub/fibonacci-server
  - docker push tasfeqhub/fibonacci-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: ""
  env: ""
  bucket_name: "elasticbeanstalk-eu-west-1-194615496736"
  bucket_path: "docker-react-app"
  on:
    branch: master  
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"